

CREATE TABLE ROLE
(
ROLE_ID INT unsigned NOT NULL AUTO_INCREMENT,
ROLE_NAME VARCHAR(25) NOT NULL,
ROLE_DESCRIPTION VARCHAR(100),
PRIMARY KEY (ROLE_ID)        
);

ALTER TABLE ROLE  AUTO_INCREMENT=2000;
COMMIT;

--INSERT TO ROLE


INSERT INTO ROLE (ROLE_NAME,ROLE_DESCRIPTION) VALUES('APP_ADMIN','ROLE FOR ADMIN TYPE USERS');
INSERT INTO ROLE (ROLE_NAME,ROLE_DESCRIPTION) VALUES('APP_DATA_ENTRY','ROLE FOR DATA ENTRY  TYPE USERS');
COMMIT;


--create a user table:

CREATE TABLE USER(
USERID VARCHAR(25) NOT NULL PRIMARY KEY,
PASSWORD VARCHAR(25) NOT NULL,
ROLE_TYPE INT unsigned NOT NULL,
FOREIGN KEY (ROLE_TYPE) REFERENCES ROLE(ROLE_ID));


--INSERT DATA TO USER

INSERT INTO USER (USERID,PASSWORD,ROLE_TYPE) VALUES ('ADMIN','SECRET',2000);
INSERT INTO USER (USERID,PASSWORD,ROLE_TYPE) VALUES ('USER1','TEST',2001);
INSERT INTO USER (USERID,PASSWORD,ROLE_TYPE) VALUES ('JOSH','josh',2000);
commit;